# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 02:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwi_real', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
