# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwi_real', '0002_auto_20171030_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
