# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwi_real', '0003_thread_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_useridea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
