# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwi_real', '0005_auto_20171030_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
    ]
